### ISSUE TITLE
Неправильное отображение игры сапёр на ноуте

### ISSUE THREAD

**Issue by mariashamoeva** [danilt2000/LuckyDiamond#4]
![image](https://github.com/danilt2000/LuckyDiamond/assets/95696949/956a39af-f412-42c5-8a6e-d6f3b008d914)

**Comment by CkutlsGit** [comment]
### **Привет!**

Исправлено, если у вас осталась эта проблема или появилась новое - сообщите еще раз.

**Всего доброго**
